# Derin Ogrenme Egitimi Soru Sayfası

Merhaba değerli katılımcı, kursa başvurun için ilk önce bu repoyu bilgisayarına indirip jupyter notebook ile çalıştırman gerekiyor, bu işlemleri tamamlaman için sana hiçbir yönerge vermiyoruz, çünkü burada amacımız hali hazırda senin bu işlemleri bilip bilmediğini yahut bunları kendi başına öğrenebiliyor musun buna bakmak. Hazırsan senin için de her şeyi hazırladık.


Bu test sayfası bir akış halinde hazırlandı, cevaplayabildiğin soruları cevapladıktan sonra kaydedip bize göndermen gerekiyor.
Hepsini tamamlamak zorunda değilsin, fakat yapamadığın kısımlar üzerinde araştırarak yeni şeylere ne kadar iyi adapte oluyorsun bunu da görmüş olacaksın.

Eğer şuan buradaysan zaten yolun büyük bir kısmını halletmişsin demektir, dosyanı sağ üst taraftaki file menüsünde "download as" sekmesinden ".ipynb" uzantılı olarak indirdikten sonra [Uludag Deep Learning mail adresi](mailto:uludagdeeplearning@gmail.com) gönderebilirsin. Eğer github sayfası açıp ödevini oraya yükledikten sonra ilgili linki bize gönderirsen ekstra puan alacaksın. 

Ödevin son kısmında opsiyonel bir bölüm daha var, gerçekten zor bir bölüm olduğundan emin olabilirsin, son bölümü seçiciliği artırmak için koyuyoruz, şayet çözersen bu senin için ekstra puan demek.

Buradaki her bir satıra hücre deniyor, shift+enter kombinasyonuyla hücreleri çalıştırabilirsin. "Sen zaten bunu biz söylemeden de basitçe çözebilirdin."

In [1]:
isim = input("Isminizi Girin= ")

Isminizi Girin= Furkan Çapar


In [2]:
print("Hosgeldin {}, öncelikle burada olduğun için çok mutluyuz, seni bu test ile karşılaştırdığımız için biz de üzgünüz fakat adil bir seçim yapmamız gerekiyor.".format(isim))

Hosgeldin Furkan Çapar, öncelikle burada olduğun için çok mutluyuz, seni bu test ile karşılaştırdığımız için biz de üzgünüz fakat adil bir seçim yapmamız gerekiyor.


## Python

In [2]:
#İleri kullanacağımız fonksiyonlar için bu hücreyi çalıştırın
import numpy
import numpy as np
import math
import sys

### Soru 0:

Python Versiyonunuzu Yazdırın.

In [4]:
print(sys.version,'Python versiyonu görüldüğü üzere 3.6.0\'dır')

3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] Python versiyonu görüldüğü üzere 3.6.0'dır


### Soru 1:

Telefon numaranızın son hanesindeki rakamdan başlayarak, son iki hanesindeki sayıya kadar devam eden bir liste oluşturun, bu listedeki sayıların ortalamasını ve toplamını yazdırın. (son iki hane sayısı 10'dan küçük olanlar için verilecek değer 70'dir.)

In [17]:
no = int(input("Telefon Numarınızı Girin= "))

Telefon Numarınızı Girin= 5467347797


### Cevap 1:

In [18]:
rakam=[int(x) for x in str(no)]
print('Telefon numarasının listesi = ',rakam)   
a=rakam[9]
b=str(rakam[8])+str(rakam[9])
b=int(b)+1
print('Telefon numarasının son iki hanesinin bir fazlası',b ,'dir. Range komutunda girilen indislerden son sayı dahil olmadığı için sayı 1 arttırıldı.')
print('Telefon numarasının son hanesi =',a,'dir.')

h=0
for sayi_listesi in range(a,b):
    sayilar =  list(range(a,b))
    h=h+sayi_listesi
print('Liste aşağıda görüldüğü gibidir ;\n',sayilar)
print('Listenin toplamını gösteren değer = {}'.format(h))
#print(h/((b-a)+1))
print('Listenin ortalaması =',h/len(sayilar))





Telefon numarasının listesi =  [5, 4, 6, 7, 3, 4, 7, 7, 9, 7]
Telefon numarasının son iki hanesinin bir fazlası 98 dir. Range komutunda girilen indislerden son sayı dahil olmadığı için sayı 1 arttırıldı.
Telefon numarasının son hanesi = 7 dir.
Liste aşağıda görüldüğü gibidir ;
 [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97]
Listenin toplamını gösteren değer = 4732
Listenin ortalaması = 52.0


### Soru 2:

Alt satırdaki yazi degiskeni olan hücreyi çalıştırın ve for döngüsüyle bu yazının her harfini bir listeye eleman olarak aktarın.

Not: Boşluklar ve noktalama işaretlerini listeye almamalısınız.

In [19]:
yazi = "uludag deeplearning teknik bir topluluktur."

### Cevap 2:

In [20]:
for x in yazi:
    yazi=list(yazi)
    s = ''.join(yazi)
print('Aşağıdaki ifade ilk formattaki her harfin listeye eklenmiş halidir:\n',yazi)      
s = s.replace(" ", "") # Boşlukları siler.
s = s.replace(".","") # Noktaları siler.
s=list(s)
print('Aşağıdaki liste ise noktalar ve boşlukların çıkarılmış olup soruda istenilen değerdir:\n ',s)



Aşağıdaki ifade ilk formattaki her harfin listeye eklenmiş halidir:
 ['u', 'l', 'u', 'd', 'a', 'g', ' ', 'd', 'e', 'e', 'p', 'l', 'e', 'a', 'r', 'n', 'i', 'n', 'g', ' ', 't', 'e', 'k', 'n', 'i', 'k', ' ', 'b', 'i', 'r', ' ', 't', 'o', 'p', 'l', 'u', 'l', 'u', 'k', 't', 'u', 'r', '.']
Aşağıdaki liste ise noktalar ve boşlukların çıkarılmış olup soruda istenilen değerdir:
  ['u', 'l', 'u', 'd', 'a', 'g', 'd', 'e', 'e', 'p', 'l', 'e', 'a', 'r', 'n', 'i', 'n', 'g', 't', 'e', 'k', 'n', 'i', 'k', 'b', 'i', 'r', 't', 'o', 'p', 'l', 'u', 'l', 'u', 'k', 't', 'u', 'r']


### Soru 3:

Sigmoid fonksiyonunu, sigmoid adını verdiğiniz fonksiyonla tanımlayınız.

![sigmoid](sigmoid.jpg)

In [21]:
# Örnek: 
def fonk_ornek(girdi):
    pass #Burası koduna dahil olmayacak.
    sonuc = islem1*islem2/girdi
    return sonuc

### Cevap 3:

In [3]:
class calculate:
    def sigmoid(x):
        sonuc = 1 / (1 + math.exp(-x))
        print(sonuc)
        return 
calculate.sigmoid(10)  # 10 yazan değere farklı rakamlar yazılarak test edilebilir.Aşağıda 2 kez daha denenmiştir.
calculate.sigmoid(-5)
calculate.sigmoid(0)
    #Ekteki sigmoid grafiği fotoğrafındakiyle eşleşen sonuçlar alınmıştır.

0.9999546021312976
0.0066928509242848554
0.5


## Numpy

### Soru 1:

5x5 boyutunda, sıfırlar, birler matrislerini oluşturun.

### Cevap 1:

In [23]:
a = numpy.zeros(shape=(5,5))
b = numpy.ones(shape=(5,5))
print(a)
print(b)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


### Soru 2:

İki farklı 5x5 random sayılardan oluşan iki matris oluşturun. Bu matrisleri matris çarpımı yöntemiyle çarpın

In [24]:
x=np.random.rand(5,5)
y=np.random.rand(5,5)
print('Birinci random değerli matrisin değeri\n',x)
print('İkinci random değerli matrisin değeri\n',y)
print('İki random değerli matrisin birbirleriyle çarpımı\n',x@y)

Birinci random değerli matrisin değeri
 [[ 0.6066474   0.46321704  0.86360567  0.69775692  0.51454235]
 [ 0.71670694  0.5126954   0.61989077  0.74139035  0.5096441 ]
 [ 0.42413402  0.04070063  0.55254375  0.69634188  0.00292978]
 [ 0.61564185  0.93065063  0.2011066   0.82346867  0.09134595]
 [ 0.82309321  0.94038606  0.94150098  0.61517961  0.00099279]]
İkinci random değerli matrisin değeri
 [[ 0.1030711   0.15496407  0.73873602  0.76354807  0.16758713]
 [ 0.90497227  0.23827636  0.8884661   0.21527843  0.99381849]
 [ 0.09788752  0.24219887  0.57438669  0.08937473  0.0167884 ]
 [ 0.35203455  0.97186029  0.58127933  0.56082507  0.74956056]
 [ 0.76998638  0.11697477  0.11367005  0.31334289  0.65029813]]
İki random değerli matrisin birbirleriyle çarpımı
 [[ 1.20808776  1.15185725  1.81982825  1.19265737  1.43413551]
 [ 1.2519405   1.1635072   1.82991288  1.28849868  1.52718157]
 [ 0.38202834  0.88633874  1.07196016  0.77343614  0.64466042]
 [ 1.28557829  1.17684388  1.88620992  1.17883948

### Soru 3:

100 Uzunluklu bir liste oluşturun, önce tek ve çift sayıları döngülerle tek ve çift adlı iki listeye ayırın, bu iki listeyi 5x10 boyutunda iki matris haline getirin.

### Cevap 3:

In [25]:
numaralar= list(range(1,101))
 
cift = []
tek = []

for x in numaralar:    
    if x % 2 == 0:    #Burdaki % mod alma işleminin temsilidir.  
        cift.append(x)
    else:       
        tek.append(x)
        
        
tek=np.array(tek)    
shape=(5,10)
tek.shape=shape  #5x10 matris şekline getiren kod bu satırın kodudur.
print('Tek sayıların matris hali aşağıdaki gibidir:\n',tek)

cift=np.array(cift)
shape=(5,10)
cift.shape=shape
print('Çift sayıların matris hali aşağıdaki gibidir:\n',cift)




Tek sayıların matris hali aşağıdaki gibidir:
 [[ 1  3  5  7  9 11 13 15 17 19]
 [21 23 25 27 29 31 33 35 37 39]
 [41 43 45 47 49 51 53 55 57 59]
 [61 63 65 67 69 71 73 75 77 79]
 [81 83 85 87 89 91 93 95 97 99]]
Çift sayıların matris hali aşağıdaki gibidir:
 [[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


### Soru 0: (Opsiyonel)

Buradaki matematiksel ifadeleri python ile yazmanızı bekliyoruz. Aşağıda yazılan fonksiyonların her biri size ekstra bazı puanlar kazandıracaktır.

![1.](1.jpg "1")

![3.](3.jpg "3")

![2.](2.jpg "2")